openapi: "3.0.2"
info:
  title: onecx-tenant external service V1
  description: This API provides endpoints to retrieve Tenants
  version: "1.0"
servers:
  - url: https://onecx-tenant
tags:
  - name: tenant
    description: External tenant service
paths:
  /v1/tenant:
      get:
        security:
          - oauth2: [ ocx-tn:read ]
        tags:
          - tenant
        description: Get tenants
        operationId: getTenantMapsByOrgId
        responses:
          "200":
            description: Tenant retrieved successfully
            content:
              "application/json":
                schema:
                  $ref: "#/components/schemas/TenantId"
          "400":
            description: Bad request
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ProblemDetailResponse'
          "404":
            description: Tenant not found
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-tn:read: Grants read access
  schemas:
    TenantId:
      required:
        - tenantId
      type: object
      properties:
        tenantId:
          type: string
          description: Id of the tenant
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
