openapi: "3.0.2"
info:
  title: onecx-tenant resolver V1
  description: This API provides endpoints to resolve an organization id into a tenant by the tenant service
  version: "1.0"
servers:
  - url: https://onecx-tenant
tags:
  - name: tenantResolver
    description: Tenant resolver service
paths:
  /v1/tenant/{orgId}:
      get:
        security:
          - oauth2: [ ocx-tn-resolver:read ]
        tags:
          - tenantResolver
        description: Get tenant by the given organization id
        operationId: getTenantByOrgId
        parameters:
          - name: orgId
            in: path
            required: true
            schema:
              type: string
        responses:
          "200":
            description: Tenant retrieved successfully
            content:
              "application/json":
                schema:
                  $ref: "#/components/schemas/TenantId"
          "404":
            description: Tenant not found
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-tn-resolver:read: Grants read access
  schemas:
    TenantId:
      required:
        - tenantId
      type: object
      properties:
        tenantId:
          type: string
          description: Id of the tenant
