apiversion: v2
name: onecx-tenant
version: 0.0.0
appversion: 0.0.0
dependencies:
- name: onecx-tenant-svc
  version: "*-0"
  repository: oci://ghcr.io/onecx/charts
  condition: "deployment.svc"
  alias: "svc"

