deployment:
  svc: true
  bff: true
  ui: true

product:
  info:
    data:
      description: "Display Tenants"
      imageUrl: ""
      iconName: "building-columns"
      displayName: "OneCX Tenant"
      basePath: /tenant
      provider: "OneCX Team"
      classifications: [ "Administration" ]
      
