= OneCX Tenant Management

== Licence
This software is licensed under the Apache License, Version 2.0.
You may obtain a copy of the license in the corresponding LICENSE file or visit the link:https://www.apache.org/licenses/LICENSE-2.0[Apache website] for more information.

== Contributing
We welcome contributions from the community.
If you would like to contribute to the development of OneCX Tenant Management Software, please follow our contribution guidelines (tbd).

== What is Tenant Management?
Tenant Management refers to storing and retrieving Tenants usable in context of OneCX applications.

== Key Features
* Tenant item Storage and Retrieval: Store and retrieve Tenants usable in context of OneCX applications.

== Issue tracking
All OneCX Tenant issues are tracked and maintained at the link:https://xyz.com[issue tracking tool].

== Overview
OneCX Tenant Software is a comprehensive solution for managing Tenants in a user-friendly and efficient manner.
It is a solution that consists of three main components: a backend service, a user interface and a backend-for-frontend (BFF) layer.

The three components of the OneCX Tenant Software are as follows:

. Tenant User Interface (UI)
  The user interface component is based on Angular, a popular JavaScript framework for building dynamic web applications.
  It offers a user-friendly and intuitive interface for interacting with the Tenant system.
  Users can perform actions such as searching and editing of Tenants.

. Tenant Backend for Frontend (BFF)
  The BFF layer acts as an intermediary between the frontend user interface and the backend service.
  It handles tasks such as data aggregation, transformation, and composition to provide an optimized API for the UI.
  The BFF layer is designed to enhance performance and simplify the integration of the frontend with the backend service.

. Tenant Backend Service (SVC)
  This component provides the core functionality.
  It handles tasks such as storage, retrieval and editing of Tenants.
  The backend is built cloud native using Quarkus.

Interfaces are based on the TM-Forum standard link:https://github.com/tmforum-apis/TMF667_Document[TMF 667].

== Getting Started
To get started with OneCX Tenant Software, please refer to the following installation and setup instructions specific to each component:

* link:https://onecx.github.io/docs/onecx-tenant/current/onecx-tenant-ui/index.html[OneCX Tenant UI (User Interface) - Getting Started]
* link:https://onecx.github.io/docs/onecx-tenant/current/onecx-tenant-bff/index.html[OneCX Tenant BFF (Backend for Frontend) - Getting Started]
* link:https://onecx.github.io/docs/onecx-tenant/current/onecx-tenant-svc/index.html[OneCX Tenant SVC (Backend) - Getting Started]

For detailed usage instructions and API documentation, please refer to the respective documentation files for each component.

== Roadmap
tbd